site_name: Riffq Docs
site_description: Documentation for the Riffq project.
site_url: https://riffq.github.io/riffq/
docs_dir: docs
site_dir: docs-site
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - FAQ: faq.md
  - Changelog: changelog.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - pysrc
          options:
            show_source: false
            show_root_heading: true
            summary: true
theme:
  name: shadcn
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ybrs/riffq
watch:
  - pysrc
  - docs
# Remove custom CSS to avoid conflicts with shadcn theme; file retained.
