name: docs
on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -r requirements.docs.txt
      - run: mkdocs build --strict
      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: mkdocs gh-deploy --force --no-history
