name: release-teleduck

on:
  push:
    tags:
      - 'rl-teleduck-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build tool
        run: pip install build
      - name: Build teleduck package
        run: |
          cd teleduck
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: teleduck/dist
          skip-existing: true
